FROM debian:10.4

RUN apt-get update \
    && apt-get install python3-pip -y \
    && python3 --version \
    && pip3 install ansible boto boto3 \
    && ansible --version \
    && apt-get install openssh-client -y \
    && && mkdir ~/.ssh \
    && echo "StrictHostKeyChecking no" > ~/.ssh/config

COPY ./ansible /ansible
COPY term.pem .

RUN chmod 400 ./term.pem

CMD mkdir ~/.ssh
CMD ansible-playbook ./ansible/ec2_deploy.yml --user ubuntu --key-file ./term.pem -vvvv
