term: &term
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build:
    <<: *term
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    <<: *term
    steps:
      - attach_workspace:
          at: .
      - run:
          command: git clone https://github.com/jarosjan/4IT572_term_ansible.git
      - run:
          name: Install `docker-compose`
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker:
          docker_layer_caching: false
      - run: |
          docker build -t my_ansible .
          docker run my_ansible

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
