term: &term
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build:
    <<: *term
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    <<: *term
    steps:
      steps:
        - attach_workspace:
            at: .
        - setup_remote_docker:
            docker_layer_caching: false
        - run:
            command: docker --tlsverify -H=$DOCKER_HOST --tlscacert=$DOCKER_CERT_PATH/ca.pem --tlscert=$DOCKER_CERT_PATH/cert.pem --tlskey=$DOCKER_CERT_PATH/key.pem build -f "Dockerfile_ubuntu" -t nehehe:latest .
        - run:
            command: git clone https://github.com/jarosjan/4IT572_term_ansible.git
        - run: |
            cd 4IT572_term_ansible
            docker build -t my_ansible .
            docker run my_ansible

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
